<?php foreach ($this->aktivnosti as $stavka) {
    $small = substr($stavka['opis'], 0, 280);?>
<div class="aktivnost">
    <div class="aktivnost_levo">
        <a href="/aktivnosti/prikaz/id/<?php print $stavka['id'];?>" class="aktivnosti_link"><h2> <?php print $stavka['ime']; ?></h2></a></br>
    <p><?php print $small; ?>...</p>
    </div>
    
    <div class="aktivnost_desno"><a href="/aktivnosti/prikaz/id/<?php print $stavka['id'];?>" class="aktivnosti_link"><button class="aktivnost_dugme">Opširnije</button></a></div>
</div>
    <?php
}
?></br>
<div style="margin:0px auto 40px auto;display:block;text-align:center;clear:both;">
    <br/>
    <a href="<?php echo $this->url(array('controller' => 'aktivnosti', 'action' => 'index', 'strana' => $this->previousPage))
?>"> Predhodna </a>
       <?php echo "" . $this->currentPage . "/" . $this->countPages; ?>
    <a href="<?php echo $this->url(array('controller' => 'aktivnosti', 'action' => 'index', 'strana' => $this->nextPage))
       ?>"> Sledeća </a>
    <br/>
</div>

