<a href="/admin/slike/"><button class="aktivnost_dugme">Administracija slika</button></a>
<a href="/admin/rezervacije/"><button class="aktivnost_dugme">Administracija rezervacije</button></a>
<a href="/admin/korisnik/"><button class="aktivnost_dugme">Administracija korisnici</button></a>
<a href="/admin/aktivnost/"><button class="aktivnost_dugme">Administracija aktivnosti</button></a>
<a href="/admin/cena/" ><button class="aktivnost_dugme">Administracija cenovnika</button></a>