<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headMeta(); ?>
        <link rel="icon" href="/img/logo/zuba-logo.png">

        <!-- Custom Fonts -->



        <!-- JS -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <script>

            $(document).ready(function () {

                $(document).on('keydown', function (e) {
                    if (e.keyCode === 27) {
                        $('#polje_pretraga').val('');
                        document.getElementById("myNav2").style.width = "0%";
                    }
                });

                $('#pretrazi').click(function () {
                    var polje = $('#polje_pretraga').val();
                    if (polje != "") {
                        $.ajax({
                            type: 'POST',
                            dataType: 'json',
                            url: 'http://zubar/ordinacija/pretraga',
                            async: false,
                            data: {pretraga: polje},
                            success: function (data)
                            {
                                $('#tabela-pretraga').find('tbody tr').remove();
                                if (data == "") {
                                    alert("Nema trazenih podataka");
                                } else {
                                    i = 0;
                                    while (data[i]) {
                                        $("#tabela-pretraga").find('tbody').append("<tr> <td>" + data[i]['ime'] + "</td><td>" + data[i]['prezime'] + "</td><td>" + data[i]['datum_rodjenja'] + "</td> <td>  <a href='/pacijenti/pacijentprikaz/id/" + data[i]['id'] + "'><button type='button' class='btn btn-primary btn-lg'>Karton</button></a></td></tr>");
                                        i++;
                                    }
                                    document.getElementById("myNav2").style.width = "82%";
                                }
                            }
                        });

                    }
                });
                $('#openNav2').click(function () {
                    document.getElementById("myNav2").style.width = "82%";
                });
                $('.closebtn2').click(function () {
                    $('#polje_pretraga').val('');
                    document.getElementById("myNav2").style.width = "0%";
                });

            });

        </script>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <body>
        <?php
        $logovan = Zend_Auth::getInstance();
        $korisnik = $logovan->getIdentity();

        if (!$logovan->hasIdentity()) {
            Zend_Auth::getInstance()->clearIdentity();
            header('Location: /index');
        }
        ?>


        <div id="wrapper">


            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/ordinacija"><?php
                        $ordinacijaid = $logovan->getIdentity()->id;
                        $orMap = new Application_Model_OrdinacijainfoMapper();
                        $logo = $orMap->getLogo($ordinacijaid);
                        if ($logo[0]['logo'] == "") {
                            echo '<img class="logo-bar" src="/img/logo/zuba-logo.png">';
                        } else {
                            echo '<img class="logo-bar" src="/img/logo/' . $logo[0]['logo'] . '">';
                        }

                        echo $logo[0]['pun_naziv'];
                        ?></a> 
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="/ordinacija/podesavanja"><i class="fa fa-user fa-fw"></i> Ordinacija</a>
                            </li>
                            
                            <li class="divider"></li>
                            <li><a href="/index/logout"><i class="fa fa-sign-out fa-fw"></i> Izlaz</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" id="polje_pretraga"  placeholder="Pretraži...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" id="pretrazi" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                <!-- /input-group -->
                            </li>
                            <li>
                                <a href="/index/index"><i class="fa fa-hospital-o fa-fw"></i> Pocetna</a>
                            </li>
                            <li>

                                <a href="#"><i class="fa fa-clipboard fa-fw"></i>Kartoteka<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="/pacijenti/dodaj"><i class="fa fa-user-plus fa-fw"></i>  Dodaj pacijenta</a> 
                                    </li>
                                    <li>
                                        <a href="/pacijenti/pacijenti"><i class="fa fa-users fa-fw"></i>  Pacijeti</a>
                                    </li>
                                    <li>
                                        <a href="/pacijenti/migracija"><i class="fa fa-random fa-fw"></i> Migracija</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="/ordinacija/statistika"><i class="fa fa-bar-chart-o fa-fw"></i> Statistika</a>
                            </li>



                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">

                            <?php echo $this->layout()->content; ?> 
                            <div id="myNav2" class="overlay2">
                                <a href="javascript:void(0)" class="closebtn2">×</a>
                                <div class="overlay-content2">

                                    <table class="table table-hover" id="tabela-pretraga">
                                        <thead>
                                            <tr>
                                                <th>Ime</th>
                                                <th>Prezime</th>
                                                <th>Datum rodjenja</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody id="bodyrez">


                                        </tbody>
                                    </table>

                                </div>
                            </div>

                        </div>

                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                    <div class="footer"></div>
                </div>



            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- Grafika -->
        <!-- <script src="../bower_components/morrisjs/morris.min.js"></script>
        <script src="../js/morris-data.js"></script> -->



        <?php echo $this->headScript(); ?>
    </body>

</html>




