    <div class="col-lg-12 margintop">
        <div class="panel panel-default">
            <div class="panel-heading">
                Svi pacijenti
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th style="text-align: center;">Ime</th>
                                <th style="text-align: center;">Prezime</th>
                                <th style="text-align: center;">Telefon</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php foreach ($this->pregled as $stavka) { ?>
                                <tr style="text-align: center;">
                                    <td><?php print $stavka['ime']; ?></td>
                                    <td><?php print $stavka['prezime']; ?></td>
                                    <td><?php print $stavka['mobilni']; ?></td>
                                    <td><a href="/pacijenti/pacijentprikaz/id/<?php print $stavka['id']; ?>"><button type="button" class="btn btn-primary">Detaljnije</button></a> </td>
                                </tr>



                            <?php } ?>

                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->



