<div class="box_sprite">
    <div class="box_sprite_inner clearfix">
                    	
         <div class="col_left">                        	
           <!-- contact form -->
           <?php echo $this->form;?>
           <!--/ contact form -->
         </div>                        
             <div class="col_right">
                    	<h2>Kontakt info</h2>
                         <div class="contact_info">
                 <div class="subtitle">Igraonica Miki, Beograd</div>
                         
                   
			<div >Bulevar Kralja Aleksandra, 328, <br>ulaz iz Slobodanke Danke Savic <br><em>Radno vreme:</em> Svaki dan 9h-21h<br></div>	
                        <div ><em>Telefon:</em> <span>065/24.00.170</span></div>
                        <div ><em>Telefon:</em> <span>011/24.00.170</span></div>
                        <div><em>Email:</em> <a href="mailto:igraonica@miki.rs" hidefocus="true" style="outline: none;">igraonica@miki.rs</a></div>
			</div>
                           
            </div>
    </div>
</div>
<h2>Naša lokacija :</h2> </br>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2831.2722122286277!2d20.49633021519539!3d44.7956407790987!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475a70807068a643%3A0xa3cce86cc5d545e0!2z0JHRg9C70LXQstCw0YAg0LrRgNCw0ZnQsCDQkNC70LXQutGB0LDQvdC00YDQsCAzMjgsINCR0LXQvtCz0YDQsNC0LCDQodGA0LHQuNGY0LA!5e0!3m2!1ssr!2s!4v1450033501849" width="1000" height="350" frameborder="0" style="border:0;margin: 0 0 0 60px;" allowfullscreen></iframe>